name: Run Web Auto Tests

on:
  push:
    branches: [ "mordern" ]
  pull_request:
    branches: [ "mordern" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore

      - name: Build the solution
        run: dotnet build

      - name: Show test methods in DLL
        run: dotnet vstest --ListTests

      - name: Run NUnit Tests
        run: dotnet test